[project]
name = "bachelor"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "kagglehub[pandas-datasets]>=0.3.13",
    "marimo>=0.15.3",
    "matplotlib>=3.10.6",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "ucimlrepo>=0.0.7",
]

[dependency-groups]
dev = [
    "python-lsp-server>=1.13.1",
]
